server:
  port: 8090
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/commerce?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: root
    jpa:
      show-sql: true 
      hibernate: 
        use-new-id-generator-mappings: false
        ddl-auto: create-drop
